- name: "Check if mig operator repo exists"
  stat:
    path: "{{ mig_operator_location }}"
  register: op_repo

- name: "Clone the mig operator repo"
  git:
    dest: "{{ mig_operator_location }}"
    repo: "{{ mig_operator_repo }}"
    version: "{{ mig_operator_branch }}"
  ignore_errors: true
  when: not op_repo.stat.exists

- assert:
    that:
      - mig_operator_release != 'latest'
    fail_msg: "latest is not a valid release for downstream CAM deployments"
  when: mig_operator_use_downstream|bool

- debug:
    msg: 
      - "Operator will deploy using OLM : {{ mig_operator_use_olm }}"
      - "Operator use downstream release : {{ mig_operator_use_downstream }}"
      - "Operator use disconnected : {{ mig_operator_use_disconnected }}"
      - "Operator will deploy using release : {{ mig_operator_release }}"

- name: "Deploy using OLM operator"
  import_tasks: operator_olm.yml
  when: mig_operator_use_olm|bool

- name: "Deploy using non-OLM operator"
  import_tasks: operator_non_olm.yml
  when: not mig_operator_use_olm|bool

- name: "Check operator status"
  import_tasks: operator_check.yml
