- name: "Extract OLM channel based on operator release"
  set_fact:
    mig_operator_channel: >-
      "{{ 'latest' if mig_operator_release == 'latest' else
      'release-v1' if mig_operator_release is version('v1.1', '<') else
      'release-v1.1' if mig_operator_release is version('v1.2', '<') else
      'latest' }}"

- set_fact:
    mig_operator_channel: "{{ mig_operator_channel|replace('\"', '') }}"
